INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(1,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(33,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(2,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(34,1,'2023-10-07','V');


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(3,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(35,1,'2023-10-07','V');


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(4,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(36,1,'2023-10-07','V');


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(5,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(37,1,'2023-10-07','V');


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(6,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(38,1,'2023-10-07','V');


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(7,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(39,1,'2023-10-07','V');


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(8,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(40,1,'2023-10-07','V');


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(9,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(41,1,'2023-10-07','V');


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(10,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(42,1,'2023-10-07','V');


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(11,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(43,1,'2023-10-07','V');


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(12,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(44,1,'2023-10-07','V');


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(13,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(45,1,'2023-10-07','V');


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(14,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(15,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(16,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(17,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(18,1,'2023-10-07','L');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(19,1,'2023-10-07','L');

-- begin vip flood

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(46,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(47,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(48,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(49,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(50,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(51,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(52,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(53,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(54,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(55,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(56,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(57,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(58,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(59,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(60,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(61,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(62,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(63,1,'2023-10-07','V');

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION)
VALUES(64,1,'2023-10-07','V');

-- end luxury flood

--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(17,1,'2023-10-07','V');

--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(18,1,'2023-10-07','V');
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(19,1,'2023-10-07','V');
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(20,1,'2023-10-07','V');
--
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(21,1,'2023-10-07','V');
--
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(22,1,'2023-10-07','V');


--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(12	,1,'2023-10-07','V');
--
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(13	,1,'2023-10-07','V');
--
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(14	,1,'2023-10-07','V');
--
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(15	,1,'2023-10-07','L');
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(16	,1,'2023-10-07','L');
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(17	,1,'2023-10-07','L');
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(18	,1,'2023-10-07','L');
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(19	,1,'2023-10-07','L');
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(20	,1,'2023-10-07','L');
--
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(21	,1,'2023-10-07','L');
--
---- october 10th for spread
--INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
--	FLIGHT_DATE,
--	REQUESTED_SECTION)
--VALUES(22	,1,'2023-10-10','L');
