INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(1,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(2,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(3,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(4	,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(5	,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(6	,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(7	,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(8	,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(9	,1,'2023-10-07','L','L',1);


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(10	,1,'2023-10-07','L','L',1);


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(11	,1,'2023-10-07','L','L',1);


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(12	,1,'2023-10-07','L','L',1);


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(13	,1,'2023-10-07','L','L',1);


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(14	,1,'2023-10-07','L','L',1);


INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(15	,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(16	,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(17	,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(18	,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(19	,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(20	,1,'2023-10-07','L','L',1);

INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(21	,1,'2023-10-07','L','L',1);

-- october 10th for spread
INSERT INTO SCHEDULE_TABLE(PASSENGER_TUID,FLIGHT_TUID,
	FLIGHT_DATE,REQUESTED_SECTION,
	SEATED_SECTION,SEAT_NUMBER)
VALUES(22	,1,'2023-10-10','L','L',1);
