DROP TABLE IF EXISTS PLANE_TABLE;

-- sql lite does auto incriment
-- automatically with INTEGER PRIMARY KEY

--contains info about each individual plane
CREATE TABLE PLANE_TABLE(
	TUID INTEGER PRIMARY KEY, 
	PLANE_ID VARCHAR,
	MAX_VIP INT,
	MAX_LUXURY INT
);


--contains info about which plane flies 
--at what time and from where
--CREATE TABLE FLIGHT_TABLE (
--	TUID INTEGER PRIMARY KEY, 
--	PLANE_TUID INTEGER ,
--	AIRPORT_CODE VARCHAR,
--	DEPART_GATE VARCHAR,
--	DEPART_TIME DATE
--	);

----person who could be in the airport
--CREATE TABLE PASSENGER_TABLE(
--	TUID INTEGER PRIMARY KEY,
--	FIRST_INITIAL CHAR,
--	MIDDLE_INITIAL CHAR,
--	LASTNAME VARCHAR,
--	PHONE_NUMBER VARCHAR
--);
--
----contains info on what does everything cost.
--CREATE TABLE FEE_TABLE (
--	TUID INTEGER PRIMARY KEY,
--	FEE_TYPE VARCHAR,
--	COST DECIMAL
--);



--CREATE TABLE SCHEDULE_TABLE (
--	TUID INTEGER PRIMARY KEY,
--	PASSENGER_TUID INTEGER ,
--	FLIGHT_TUID INTEGER ,
--	FLIGHT_DATE,
--	REQUESTED_SECTION,
--	SEATED_SECTION,
--	SEAT_NUMBER,
--	FOREIGN KEY(PASSENGER_TUID) 
--		REFERENCES(PASSENGER_TABLE)
--	FOREIGN KEY (FLIGHT_TUID)
--		REFERENCES(FLIGHT_TABLE)
--	);
