--this file is used to delete all non view tables from the database
DROP TABLE IF EXISTS PLANE_TABLE;
DROP TABLE IF EXISTS FLIGHT_TABLE;
DROP TABLE IF EXISTS PASSENGER_TABLE;
DROP TABLE IF EXISTS FEE_TABLE;
DROP TABLE IF EXISTS SCHEDULE_TABLE_DATA;
